let c=Math.random()
console.log(c)
let a=Math.round(5.5)
console.log(a)
let b=Math.floor(5.1)
console.log(b)
let d =Math.ceil(5.3)
console.log(d)
let e =Math.pow(2,3)
console.log(e)
let f=Math.sqrt(4)
console.log(f)
let g =Math.min(1,2,3,4,5)
console.log(g)